/**
 * The gemini adapter — wires Google's open-source `gemini` CLI to kelbrin.
 *
 * VERIFIED integration points (google-gemini/gemini-cli, docs read 2026-07-11):
 *   1. Lifecycle hooks live in `~/.gemini/settings.json` under a top-level
 *      `hooks` object keyed by event name — NOT in `~/.gemini/hooks.json`, which
 *      belongs to Antigravity (`agy`). The two adapters therefore never collide.
 *      `AfterAgent` fires once per turn on the agent's final response (→ done);
 *      `Notification` fires on system alerts such as tool-permission prompts
 *      (→ blocked). Payload arrives on STDIN as JSON.
 *   2. Custom slash commands are TOML files under `~/.gemini/commands/<name>.toml`
 *      with a required `prompt` key (optional `description`); `!{...}` embeds a
 *      shell command's output and `{{args}}` injects user arguments. kelbrin writes
 *      `kelbrin.toml` so `/kelbrin <args>` runs the kelbrin CLI from inside Gemini.
 *
 * Read-aloud reads the AfterAgent payload's VERIFIED `prompt_response` field
 * directly (the documented "final text generated by the agent"), mirroring the
 * codex adapter. The `transcript_path` transcript format is officially
 * undocumented and mid-migration to JSONL (google-gemini/gemini-cli#15292), so
 * kelbrin does not parse it — a documented field beats a speculative parser.
 *
 * `normalize`/`readLastResponse`/`detect` run inside (or adjacent to) a hook and
 * MUST NOT throw: every read degrades defensively. `wire` goes through
 * {@link wireJsonFile}/{@link wireTextFile} so every change is previewable;
 * `unwire` is surgical — {@link unwireJsonFile} strips only kelbrin's own hook
 * entries via {@link removeKelbrinHooks}, and {@link unwireCreatedFile} deletes
 * the command file kelbrin created — so edits a user makes after wiring survive.
 */

import { join } from "node:path";

import type { EventName } from "../core/config.ts";
import type { KelbrinEvent } from "../core/events.ts";
import { projectLabel } from "../core/events.ts";
import { unwireCreatedFile, unwireJsonFile, wireJsonFile, wireTextFile } from "./diffwire.ts";
import { legacyCommandVariant, removeKelbrinHooks } from "./hooks.ts";
import type { Adapter, AdapterDeps, Detection, WireResult } from "./types.ts";

const ID = "gemini";
const TITLE = "Gemini";
const BINARY = "gemini";
const CONFIG_DIR = ".gemini";
const SETTINGS_FILE = "settings.json";
const COMMANDS_DIR = "commands";
const COMMAND_FILE = "kelbrin.toml";
/** Slash-command file written by pre-rename (hollr) versions. */
const LEGACY_COMMAND_FILE = "hollr.toml";
const SETTINGS_LEDGER_KEY = "gemini:settings";
const COMMAND_LEDGER_KEY = "gemini:command";

const HOOK_AFTER_AGENT = "AfterAgent";
const HOOK_NOTIFICATION = "Notification";
const HOOK_TYPE_COMMAND = "command";

const DONE_COMMAND = "kelbrin emit --agent gemini --event done --payload-stdin";
const BLOCKED_COMMAND =
  "kelbrin emit --agent gemini --event blocked --payload-stdin";

/** VERIFIED AfterAgent field carrying the agent's final response text. */
const LAST_RESPONSE_FIELD = "prompt_response";

/**
 * The `/kelbrin` custom command kelbrin owns. `!{...}` runs the shell command and
 * embeds its stdout; `{{args}}` is shell-escaped inside the block. Managed by
 * kelbrin and fully reversible via `kelbrin uninstall`.
 */
const COMMAND_TEMPLATE = `# Managed by kelbrin — reversible via \`kelbrin uninstall\`. Do not edit by hand.
description = "Run the kelbrin CLI (voice + desktop notifications) from inside Gemini"
prompt = """
Below is the raw output of the kelbrin command-line tool. Relay it to the user as-is.

!{kelbrin {{args}}}
"""
`;

type JsonObject = Record<string, unknown>;

function isRecord(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function settingsPath(deps: AdapterDeps): string {
  return join(deps.home, CONFIG_DIR, SETTINGS_FILE);
}

function commandPath(deps: AdapterDeps): string {
  return join(deps.home, CONFIG_DIR, COMMANDS_DIR, COMMAND_FILE);
}

// --- wiring -----------------------------------------------------------------

/** True when a hook-array entry already carries `command`. */
function entryHasCommand(entry: unknown, command: string): boolean {
  if (!isRecord(entry) || !Array.isArray(entry.hooks)) {
    return false;
  }
  return entry.hooks.some((hook) => isRecord(hook) && hook.command === command);
}

/** Append kelbrin's hook entry for `command` unless it is already present. */
function appendKelbrinHook(existing: unknown, command: string): unknown[] {
  const list = Array.isArray(existing) ? existing : [];
  if (list.some((entry) => entryHasCommand(entry, command))) {
    return list;
  }
  return [...list, { hooks: [{ type: HOOK_TYPE_COMMAND, command }] }];
}

/**
 * Idempotent mutation adding the AfterAgent (done) and Notification (blocked)
 * hooks while preserving every unrelated hook event and any pre-existing entries.
 */
function addHooks(json: JsonObject): JsonObject {
  const hooks = isRecord(json.hooks) ? json.hooks : {};
  return {
    ...json,
    hooks: {
      ...hooks,
      [HOOK_AFTER_AGENT]: appendKelbrinHook(hooks[HOOK_AFTER_AGENT], DONE_COMMAND),
      [HOOK_NOTIFICATION]: appendKelbrinHook(
        hooks[HOOK_NOTIFICATION],
        BLOCKED_COMMAND,
      ),
    },
  };
}

/** Concatenate the non-empty per-file diffs. */
function joinDiffs(settingsDiff: string, commandDiff: string): string {
  return [settingsDiff, commandDiff].filter((diff) => diff.length > 0).join("\n");
}

// --- surgical unwire ---------------------------------------------------------

/**
 * The hook commands kelbrin's own wiring can append, plus the pre-rename
 * (hollr) forms old installs wrote — both count as ours for strip/unwire.
 */
const KELBRIN_COMMANDS: ReadonlySet<string> = new Set([
  DONE_COMMAND,
  BLOCKED_COMMAND,
  legacyCommandVariant(DONE_COMMAND),
  legacyCommandVariant(BLOCKED_COMMAND),
]);

/** Shape-A entry (`{ hooks: [{ command }] }`) carrying one of kelbrin's commands. */
function isKelbrinEntry(entry: unknown): boolean {
  return (
    isRecord(entry) &&
    Array.isArray(entry.hooks) &&
    entry.hooks.some(
      (hook) => isRecord(hook) && typeof hook.command === "string" && KELBRIN_COMMANDS.has(hook.command),
    )
  );
}

/** Strip kelbrin's AfterAgent/Notification hook entries, preserving everything else. */
function removeHooks(json: JsonObject): JsonObject {
  return removeKelbrinHooks(json, [HOOK_AFTER_AGENT, HOOK_NOTIFICATION], isKelbrinEntry);
}

// --- adapter ----------------------------------------------------------------

export const gemini: Adapter = {
  id: ID,
  title: TITLE,
  tagline: "Google Gemini CLI — AfterAgent done, Notification blocked, /kelbrin command",
  capabilities: {
    done: true,
    blocked: true,
    readAloud: true,
    slashCommand: true,
    instructionInjection: true,
  },

  memoryPath(deps: AdapterDeps): string {
    return join(deps.home, CONFIG_DIR, "GEMINI.md");
  },

  detect(deps: AdapterDeps): Promise<Detection> {
    // Primary (and only) positive signal is the binary on PATH: `~/.gemini`
    // exists for Antigravity too, so its presence must not false-positive here.
    const installed = deps.which(BINARY) !== null;
    const detection: Detection = { installed };
    if (installed) {
      detection.configPath = settingsPath(deps);
    }
    return Promise.resolve(detection);
  },

  wire(deps: AdapterDeps): Promise<WireResult> {
    const settingsOp = wireJsonFile(
      settingsPath(deps),
      (json) => addHooks(removeHooks(json)),
      SETTINGS_LEDGER_KEY,
    );
    const commandOp = wireTextFile(
      commandPath(deps),
      COMMAND_TEMPLATE,
      COMMAND_LEDGER_KEY,
    );
    const result: WireResult = {
      changed: settingsOp.changed || commandOp.changed,
      diff: joinDiffs(settingsOp.diff, commandOp.diff),
      warnings: [],
    };
    settingsOp.apply();
    commandOp.apply();
    return Promise.resolve(result);
  },

  unwire(deps: AdapterDeps): Promise<void> {
    unwireJsonFile(settingsPath(deps), removeHooks, SETTINGS_LEDGER_KEY);
    unwireCreatedFile(
      join(deps.home, CONFIG_DIR, COMMANDS_DIR, LEGACY_COMMAND_FILE),
      COMMAND_LEDGER_KEY,
    );
    unwireCreatedFile(commandPath(deps), COMMAND_LEDGER_KEY);
    return Promise.resolve();
  },

  normalize(raw: unknown, eventHint: EventName): KelbrinEvent | null {
    if (!isRecord(raw)) {
      return null;
    }
    const cwd = typeof raw.cwd === "string" ? raw.cwd : "";
    return {
      v: 1,
      ts: new Date().toISOString(),
      agent: ID,
      agentTitle: TITLE,
      event: eventHint,
      cwd,
      project: projectLabel(cwd),
      summary: typeof raw.message === "string" ? raw.message : "",
      lastResponse: null,
    };
  },

  readLastResponse(raw: unknown): Promise<string | null> {
    if (!isRecord(raw)) {
      return Promise.resolve(null);
    }
    const response = raw[LAST_RESPONSE_FIELD];
    return Promise.resolve(typeof response === "string" ? response : null);
  },
};
